package com.company;

public enum Right {
    CREATE_USER,
    REMOVE_USER,

    EDIT_USER_FULL,
    CREATE_POST_FULL,
    EDIT_POST_FULL,
    PUBLISH_POST_FULL,
    DELETE_POST_FULL,
    MANAGE_COMMENTS_FULL,

    EDIT_USER_LIMITED,
    CREATE_POST_LIMITED,
    EDIT_POST_LIMITED,
    PUBLISH_POST_LIMITED,
    DELETE_POST_LIMITED,
    MANAGE_COMMENTS_LIMITED,

    MODIFY_CORE_FILES,
    MANAGE_USERS
}
